name: SQLsmith
on:
  schedule:
    # run daily 20:00 on main branch
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      seed:
        description: 'SQLsmith seed'
        default: '\$((16#\$(openssl rand -hex 3)))'
        type: string
        required: true
      os:
        description: 'The OS to run on'
        required: true
        default: 'ubuntu-20.04'
        type: choice
        options:
          - 'ubuntu-20.04'
          - 'ubuntu-latest'
      compiler:
        description: 'Compiler to use'
        required: true
        type: choice
        default: 'gcc'
        options:
          - 'gcc'
          - 'clang'
      build_type:
        description: 'Build type'
        required: true
        type: choice
        default: 'Debug'
        options:
          - 'Debug'
          - 'Release'
      pg:
        description: 'PostgreSQL version'
        required: true
        type: string
        default: '14.2'
      tsdb_build_args:
        description: 'Extra CMake build arguments for TimescaleDB'
        required: false
        type: string
        default: ''
      number_of_runs:
        description: 'Number of SQLsmith runs'
        type: number
        default: 10
        required: true
      max_queries:
        description: 'Max number of SQLsmith queries'
        type: number
        default: 10000
        required: true
  push:
    branches:
      - sqlsmith
jobs:
  regress:
    name: SQLsmith PG${{ github.event.inputs.pg }}
    runs-on: ${{ github.event.inputs.os }}
    env:
      PG_SRC_DIR: pgbuild
      PG_INSTALL_DIR: postgresql

    steps:
    - name: Install Linux Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install flex bison systemd-coredump gdb clang-9 llvm-9 llvm-9-dev llvm-9-tools build-essential autoconf autoconf-archive libpqxx-dev libboost-regex-dev libsqlite3-dev

    # this workflow depends on the cached postgres build from the main regression
    # workflow since that workflow runs daily there should always be a cache hit
    - name: Cache PostgreSQL ${{ github.event.inputs.pg }}
      id: cache-postgresql
      uses: actions/cache@v2
      with:
        path: ~/${{ env.PG_SRC_DIR }}
        key: ${{ github.event.inputs.os }}-postgresql-${{ github.event.inputs.pg }}-${{ github.event.inputs.compiler }}-${{ github.event.inputs.build_type }}

    # we abort on cache miss 
    - name: Abort on cache miss
      if: steps.cache-postgresql.outputs.cache-hit != 'true'
      run: false

    - name: Install PostgreSQL ${{ github.event.inputs.pg }} ${{ github.event.inputs.build_type }}
      run: |
        make -C ~/$PG_SRC_DIR install
        make -C ~/$PG_SRC_DIR/contrib/postgres_fdw install

    - name: Checkout TimescaleDB
      uses: actions/checkout@v2

    - name: Build TimescaleDB
      run: |
        ./bootstrap -DCMAKE_BUILD_TYPE=${{ github.event.inputs.build_type }} -DPG_SOURCE_DIR=~/$PG_SRC_DIR -DPG_PATH=~/$PG_INSTALL_DIR ${{ github.event.inputs.tsdb_build_args }}
        make -C build
        make -C build install

    - name: Checkout sqlsmith
      uses: actions/checkout@v2
      with:
        repository: 'timescale/sqlsmith'
        path: 'sqlsmith'
        ref: 'timescaledb'

    - name: Build SQLsmith
      run: |
        cd sqlsmith
        autoreconf -i
        ./configure
        make

    - name: Setup test environment
      run: |
        mkdir ~/pgdata
        ~/$PG_INSTALL_DIR/bin/initdb ~/pgdata
        ~/$PG_INSTALL_DIR/bin/pg_ctl -D ~/pgdata start -o "-cshared_preload_libraries=timescaledb" -o "-cmax_connections=200" -o "-cmax_prepared_transactions=100"
        psql -h /tmp postgres -c 'CREATE DATABASE smith;'
        psql -h /tmp smith -c 'CREATE EXTENSION timescaledb;'
        psql -h /tmp smith -c '\i ${{ github.workspace }}/tsl/test/shared/sql/include/shared_setup.sql'

    # we run these in a loop to reinitialize the random number generator
    # 10 times 10000 queries seems to take roughly 40 minutes in CI
    - name: Run SQLsmith
      run: |
        cd sqlsmith
        for i in `seq 1 ${{ github.event.inputs.number_of_runs }}`; do ./sqlsmith --seed=${{ github.event.inputs.seed}} --exclude-catalog --target="host=/tmp dbname=smith" --max-queries=${{ github.event.inputs.max_queries }} > tee queries-$i-${{ github.event.inputs-seed }}.log; done

    - name: Check for coredumps
      if: always()
      id: collectlogs
      run: |
        # wait for in progress coredumps
        sleep 10
        if coredumpctl list; then
          echo "::set-output name=coredumps::true"
          false
        fi

    - name: Stack trace
      if: always() && steps.collectlogs.outputs.coredumps == 'true'
      run: |
        echo "bt full" | sudo coredumpctl gdb
        ./scripts/bundle_coredumps.sh
        false

    - name: Upload Coredumps
      if: always() && steps.collectlogs.outputs.coredumps == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: Coredumps sqlsmith ${{ github.event.inputs.os }} PG${{ github.event.inputs.pg }}
        path: coredumps

    - name: Upload query logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: SQL query logs ${{ github.event.inputs.os }} PG${{ github.event.inputs.pg }}
        path: queries-*.log
